app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

/* Auth */
Route::controller( 'auth', 'Auth\AuthController', [
    'getRegister' => 'auth.register',
    'getLogin'    => 'auth.login',
]);

Route::get( 'account/settings', ['as' => 'account.settings', 'uses' => 'Front\AccountController@getSettings'] );
Route::post( 'account/settings/email', 'Front\AccountController@postEmail' );
Route::post( 'account/settings/password', 'Front\AccountController@postPassword' );

/* Character */
Route::get( 'character/select/{role_id}', 'Front\CharacterController@getSelect' );

// Password reset link request routes...
Route::post( 'password/email', 'Auth\PasswordController@postEmail' );

// Password reset routes...
Route::get( 'password/reset/{token}', 'Auth\PasswordController@getReset' );
Route::post( 'password/reset', 'Auth\PasswordController@postReset' );

/* News */
Route::get( '/', ['as' => 'news.index', 'uses' => 'Front\NewsController@getIndex'] );

/* Shop */
Route::get( 'shop', ['as' => 'shop.index', 'uses' => 'Front\ShopController@getIndex'] );
Route::post( 'shop/purchase/{shop}', 'Front\ShopController@postPurchase' );
Route::post( 'shop/gift/{shop}', 'Front\ShopController@postGift' );
Route::get( 'shop/mask/{shop_mask}', ['as' => 'shop.mask', 'uses' => 'Front\ShopController@getMask'] );

/* Donate */
Route::get( 'donate', ['as' => 'donate.index', 'uses' => 'Front\DonateController@getIndex'] );
Route::post( 'donate/paypal', 'Front\DonateController@postPaypalSubmit' );
Route::get( 'donate/paypal/complete', 'Front\DonateController@postPayPalComplete' );
Route::get( 'donate/paymentwall', 'Front\DonateController@getPaymentwall' );

/* Vote */
Route::get( 'vote', ['as' => 'vote.index', 'uses' => 'Front\VoteController@getIndex'] );
Route::get( 'vote/success/{vote}', ['as' => 'vote.success', 'uses' => 'Front\VoteController@getSuccess'] );
Route::post( 'vote/check/{vote}', 'Front\VoteController@postCheck' );

/* Voucher */
Route::get( 'voucher', ['as' => 'voucher.index', 'uses' => 'Front\VoucherController@getIndex'] );
Route::post( 'voucher/redeem', 'Front\VoucherController@postRedeem' );

/* Services */
Route::get( 'services', ['as' => 'services.index', 'uses' => 'Front\ServicesController@getIndex'] );
Route::post( 'services/{service}', 'Front\ServicesController@postPurchase' );

/* Ranking */
Route::get( 'ranking', 'Front\RankingController@getIndex' );
Route::get( 'ranking/player/{sub}', ['as' => 'ranking.index', 'uses' => 'Front\RankingController@getPlayer'] );
Route::get( 'ranking/faction', function(){
    return redirect( 'ranking/faction/level' );
});
Route::get( 'ranking/faction/{sub}', ['as' => 'ranking.index', 'uses' => 'Front\RankingController@getFaction'] );

/* Not Working */
//Route::get( 'ranking/territory', ['as' => 'ranking.index', 'uses' => 'Front\RankingController@getTerritory'] );

/* Admin */
Route::group( ['prefix' => 'admin', 'middleware' => ['auth', 'admin'] ], function() {

    Route::get( '/', ['as' => 'admin.index', 'uses' => 'Admin\IndexController@getIndex'] );

    /* Members */
    Route::get( 'members/manage', ['as' => 'admin.members.manage', 'uses' => 'Admin\MembersController@getManage'] );
    Route::post( 'members/balance/{user}', 'Admin\MembersController@postBalance' );
    Route::post( 'members/search', 'Admin\MembersController@postSearch' );

    /* System */
    Route::group( ['prefix' => 'system', 'as' => 'admin.system.'], function() {

        Route::get( 'settings', ['as' => 'settings', 'uses' => 'Admin\SystemController@getSettings'] );
        Route::post( 'settings', 'Admin\SystemController@postSettings' );
        Route::get( 'apps', ['as' => 'apps', 'uses' => 'Admin\SystemController@getApps'] );
        Route::post( 'apps', 'Admin\SystemController@postApps' );

//        Route::get( 'widget', ['as' => 'widget', 'uses' => 'Admin\SystemController@getWidget'] );
//        Route::post( 'widget', 'Admin\SystemController@postWidget' );

    });

    /* News */
    Route::get( 'news/settings', ['as' => 'admin.news.settings', 'uses' => 'Admin\NewsController@getSettings'] );
    Route::post( 'news/settings', 'Admin\NewsController@postSettings' );
    Route::resource( 'news', 'Admin\NewsController' );

    /* Shop */
    Route::get( 'shop/settings', ['as' => 'admin.shop.settings', 'uses' => 'Admin\ShopController@getSettings'] );
    Route::post( 'shop/settings', 'Admin\ShopController@postSettings' );
    Route::resource( 'shop', 'Admin\ShopController' );

    /* Donate */
    Route::get( 'donate/settings', ['as' => 'admin.donate.settings', 'uses' => 'Admin\DonateController@getSettings'] );
    Route::post( 'donate/paypal', 'Admin\DonateController@postPaypalSettings' );
    Route::post( 'donate/paymentwall', 'Admin\DonateController@postPaymentwallSettings' );

    /* Voucher */
    Route::resource( 'voucher', 'Admin\VoucherController' );

    /* Vote */
    Route::resource( 'vote', 'Admin\VoteController' );

    /* Services */
    Route::get( 'services', ['as' => 'admin.services.edit', 'uses' => 'Admin\ServicesController@getEdit'] );
    Route::post( 'services', 'Admin\ServicesController@postEdit' );
    Route::get( 'services/settings', ['as' => 'admin.services.settings', 'uses' => 'Admin\ServicesController@getSettings'] );
    Route::post( 'services/settings', 'Admin\ServicesController@postSettings' );

    /* Ranking */
    Route::get( 'ranking/settings', ['as' => 'admin.ranking.settings', 'uses' => 'Admin\RankingController@getSettings'] );
    Route::post( 'ranking/settings', 'Admin\RankingController@postSettings' );

    /* Management */
    Route::get( 'management/gm', ['as' => 'admin.management.gm.view', 'uses' => 'Admin\ManagementController@getGM'] );
    Route::post( 'management/gm', 'Admin\ManagementController@postGM' );
    Route::get( 'management/gm/edit/{user}', ['as' => 'admin.management.gm.edit', 'uses' => 'Admin\ManagementController@getGMEdit'] );
    Route::post( 'management/gm/edit/{user}', 'Admin\ManagementController@postGMEdit' );
    Route::get( 'management/gm/remove/{user}', 'Admin\ManagementController@getGMRemove' );
    Route::get( 'management/chat/watch', ['as' => 'admin.management.chat.watch', 'uses' => 'Admin\ManagementController@getChatWatch'] );
    Route::post( 'management/chat/logs', 'Admin\ManagementController@postChatLogs' );
    Route::get( 'management/chat/settings', ['as' => 'admin.management.chat.settings', 'uses' => 'Admin\ManagementController@getChatSettings'] );
    Route::post( 'management/chat/settings', 'Admin\ManagementController@postChatSettings' );
    Route::controller( 'management', 'Admin\ManagementController', [
        'getBroadcast' => 'admin.management.broadcast',
        'getMailer' => 'admin.management.mailer',
        'getForbid' => 'admin.management.forbid'
    ]);
});

/* Installer */
Route::group( ['prefix' => 'admin/install', 'as' => 'admin.installer.'], function()
{
    Route::group( ['middleware' => 'installed'], function()
    {
        get( '/', [
            'as' => 'welcome',
            'uses' => 'Admin\InstallController@welcome'
        ]);

        get( 'settings', [
            'as' => 'settings',
            'uses' => 'Admin\InstallController@getSettings'
        ]);

        post( 'setup', [
            'as' => 'settings.save',
            'uses' => 'Admin\InstallController@postSettings'
        ]);

        /*get( 'environment', [
            'as' => 'environment',
            'uses' => 'Admin\InstallController@environment'
        ]);

        post( 'environment/save', [
            'as' => 'environment.save',
            'uses' => 'Admin\InstallController@save'
        ]);

        get( 'requirements', [
            'as' => 'requirements',
            'uses' => 'Admin\InstallController@requirements'
        ]);

        get( 'permissions', [
            'as' => 'permissions',
            'uses' => 'Admin\InstallController@permissions'
        ]);

        get( 'database', [
            'as' => 'database',
            'uses' => 'Admin\InstallController@database'
        ]);*/

        get( 'complete', [
            'as' => 'complete',
            'uses' => 'Admin\InstallController@complete'
        ]);
    });
});

app/Http/Controllers/Admin/ShopController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\ShopItemRequest;
use App\ShopItem;
use Efriandika\LaravelSettings\Facades\Settings;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class ShopController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        pagetitle( [ trans( 'shop.index' ), settings( 'server_name' ) ] );
        $items = ShopItem::paginate( settings( 'shop_items_per_page' ) );
        return view( 'admin.shop.view', compact( 'items' ) );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        pagetitle( [ trans( 'shop.create' ), settings( 'server_name' ) ] );
        return view( 'admin.shop.create' );
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param ShopItemRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store( ShopItemRequest $request )
    {
        ShopItem::create( $request->all() );

        flash()->success( trans( 'shop.create_success' ) );

        return redirect( 'admin/shop' );
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param ShopItem $item
     * @return \Illuminate\Http\Response
     */
    public function edit( ShopItem $item )
    {
        pagetitle( [ trans( 'shop.edit', ['name' => $item->name] ), settings( 'server_name' ) ] );
        return view( 'admin.shop.edit', compact( 'item' ) );
    }

    /**
     * Update the specified resource in storage.
     *
     * @param ShopItem $item
     * @param ShopItemRequest $request
     * @return \Illuminate\Http\Response
     */
    public function update( ShopItem $item, ShopItemRequest $request )
    {
        $item->update( $request->all() );

        flash()->success( trans( 'shop.edit_success' ) );

        return redirect( 'admin/shop' );
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Request $request
     * @param ShopItem $item
     */
    public function destroy( Request $request, ShopItem $item )
    {
        if ( $request->ajax() )
        {
            $item->delete();
        }
    }

    public function getSettings()
    {
        pagetitle( [ trans( 'main.settings' ), trans( 'main.apps.shop' ), settings( 'server_name' ) ] );
        return view( 'admin.shop.settings' );
    }

    public function postSettings( Request $request )
    {
        Settings::set( 'shop_items_per_page', $request->items_per_page );

        flash()->success( trans( 'main.settings_saved' ) );

        return redirect( 'admin/shop' );
    }
}

app/Http/Controllers/Front/ShopController.php
<?php

namespace App\Http\Controllers\Front;

use App\ShopItem;
use Huludini\PerfectWorldAPI\API;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class ShopController extends Controller
{
    public function __construct()
    {
        $this->middleware( 'auth' );

        $this->middleware( 'selected.character', ['only' => ['postPurchase', 'postGift'] ] );

        $this->middleware( 'server.online', ['only' => 'postPurchase'] );
    }

    public function getIndex()
    {
        pagetitle( [ trans( 'main.apps.shop' ), settings( 'server_name' ) ] );
        $items = ShopItem::paginate( settings( 'shop_items_per_page' ) );
        return view( 'front.shop.index', compact( 'items' ) );
    }

    public function getMask( $mask )
    {
        pagetitle( [ trans( 'main.apps.shop' ), settings( 'server_name' ) ] );
        $items = ShopItem::where( 'mask', $mask )->paginate( settings( 'shop_items_per_page' ) );
        return view( 'front.shop.index', compact( 'items' ) );
    }

    public function postPurchase( ShopItem $item )
    {
        $user = Auth::user();
        $item_price = ( $item->discount > 0 ) ? $item->price - ( $item->price / 100 * $item->discount ) : $item->price;

        if ( $user->money >= $item_price )
        {
            $api = new API();
            $mail = array(
                'title' => trans( 'shop.mail_item.title', ['name' => settings( 'server_name' )] ),
                'message' => trans( 'shop.mail_item.message', ['name' => $item->name, 'count' => $item->count, 'staff' => settings( 'server_name' )] ),
                'money' => 0,
                'item' => array(
                    'id' => $item->item_id,
                    'pos' => 0,
                    'count' => $item->count,
                    'max_count' => $item->max_count,
                    'data' => $item->octet,
                    'proctype' => $item->protection_type,
                    'expire_date' => $item->expire_date,
                    'guid1' => 0,
                    'guid2' => 0,
                    'mask' => $item->mask,
                ),
            );
            $api->sendMail( Auth::user()->characterId(), $mail['title'], $mail['message'], $mail['item'], $mail['money'] );
            $user->money = $user->money - $item_price;
            $user->save();
            flash()->success( trans( 'shop.purchase_complete', ['name' => $item->name] ) );
        }
        else
        {
            flash()->error( trans( 'main.not_enough', ['currency' => strtolower( settings( 'currency_name' ) )] ) );
        }
        return redirect()->back();
    }

    public function postGift( Request $request, ShopItem $item )
    {
        $this->validate($request, [
            'friends' => 'required|array|min:1',
        ]);

        $user = Auth::user();
        $item_price = ( $item->discount > 0 ) ? ( $item->price - ( $item->price / 100 * $item->discount ) ) : $item->price;

        if ( $user->money > $item_price )
        {
            $api = new API();
            $mail = array(
                'title' => trans( 'shop.gift_item.title' ),
                'message' => trans( 'shop.gift_item.message', ['name' => $item->name, 'count' => $item->count, 'player' => $user->characterName()] ),
                'money' => 0,
                'item' => array(
                    'id' => $item->item_id,
                    'pos' => 0,
                    'count' => $item->count,
                    'max_count' => $item->max_count,
                    'data' => $item->octet,
                    'proctype' => $item->protection_type,
                    'expire_date' => $item->expire_date,
                    'guid1' => 0,
                    'guid2' => 0,
                    'mask' => $item->mask,
                ),
            );
            foreach ( $request->friends as $friend )
            {
                if ( $api->sendMail( $friend, $mail['title'], $mail['message'], $mail['item'], $mail['money'] ) )
                {
                    //TODO Add notifications
                    $user->money = $user->money - $item_price;
                    $user->save();
                    flash()->success( trans( 'shop.gift_complete', ['name' => $item->name, 'count' => count( $request->friends )] ) );
                }
                else
                {
                    flash()->error( trans( 'main.server_not_online' ) );
                }
            }
        }
        else
        {
            flash()->error( trans( 'main.not_enough', ['currency' => strtolower( settings( 'currency_name' ) )] ) );
        }
        return redirect()->back();
    }
}

resources/views/admin/shop/create.blade.php
@extends( 'admin.header' )

@section( 'content' )
    <div class="portlet light bordered">
        <div class="portlet-body form">
            {!! Form::model( $item = new \App\ShopItem(), ['url' => route( 'admin.shop.index' ), 'class' => 'form-horizontal'] ) !!}
                @include( 'admin.shop.form', [ 'submitButtonText' => trans( 'shop.add_button' ) ] )
            {!! Form::close() !!}
        </div>
    </div>
@endsection

resources/views/admin/shop/edit.blade.php
@extends( 'admin.header' )

@section( 'content' )
    <div class="portlet light bordered">
        <div class="portlet-body form">
            {!! Form::model( $item, [ 'method' => 'PATCH', 'action' => ['Admin\ShopController@update', $item->id], 'class' => 'form-horizontal' ] ) !!}
                @include( 'admin.shop.form', [ 'submitButtonText' => trans( 'shop.update_button' ) ] )
            {!! Form::close() !!}
        </div>
    </div>
@endsection

resources/views/admin/shop/form.blade.php
<div class="form-body">
    <div class="form-group form-md-line-input">
        {!! Form::label( 'name', trans( 'shop.fields.name' ), ['class' => 'col-md-2 control-label'] ) !!}
        <div class="col-md-9">
            {!! Form::text( 'name', NULL, ['class' => 'form-control'] ) !!}
            <div class="form-control-focus"> </div>
        </div>
    </div>

    <div class="form-group form-md-line-input">
        {!! Form::label( 'price', trans( 'shop.fields.price' ), ['class' => 'col-md-2 control-label'] ) !!}
        <div class="col-md-9">
            {!! Form::input( 'number', 'price', NULL, ['class' => 'form-control'] ) !!}
            <div class="form-control-focus"> </div>
        </div>
    </div>

    <div class="form-group form-md-line-input">
        {!! Form::label( 'item_id', trans( 'shop.fields.item_id' ), ['class' => 'col-md-2 control-label'] ) !!}
        <div class="col-md-9">
            {!! Form::input( 'number', 'item_id', NULL, ['class' => 'form-control'] ) !!}
            <div class="form-control-focus"> </div>
        </div>
    </div>

    <div class="form-group form-md-line-input">
        {!! Form::label( 'octet', trans( 'shop.fields.octet' ), ['class' => 'col-md-2 control-label'] ) !!}
        <div class="col-md-9">
            {!! Form::text( 'octet', NULL, ['class' => 'form-control'] ) !!}
            <div class="form-control-focus"> </div>
        </div>
    </div>

    <div class="form-group form-md-line-input">
        {!! Form::label( 'mask', trans( 'shop.fields.mask' ), ['class' => 'col-md-2 control-label'] ) !!}
        <div class="col-md-9">
            {!! Form::select( 'mask', $masks, NULL, ['class' => 'form-control'] ) !!}
            <div class="form-control-focus"> </div>
        </div>
    </div>

    <div class="form-group form-md-line-input">
        {!! Form::label( 'count', trans( 'shop.fields.count' ), ['class' => 'col-md-2 control-label'] ) !!}
        <div class="col-md-9">
            {!! Form::input( 'number', 'count', NULL, ['class' => 'form-control'] ) !!}
            <div class="form-control-focus"> </div>
        </div>
    </div>

    <div class="form-group form-md-line-input">
        {!! Form::label( 'max_count', trans( 'shop.fields.max_count' ), ['class' => 'col-md-2 control-label'] ) !!}
        <div class="col-md-9">
            {!! Form::input( 'number', 'max_count', NULL, ['class' => 'form-control'] ) !!}
            <div class="form-control-focus"> </div>
        </div>
    </div>

    <div class="form-group form-md-line-input">
        {!! Form::label( 'protection_type', trans( 'shop.fields.protection_type' ), ['class' => 'col-md-2 control-label'] ) !!}
        <div class="col-md-9">
            {!! Form::input( 'number', 'protection_type', NULL, ['class' => 'form-control'] ) !!}
            <div class="form-control-focus"> </div>
        </div>
    </div>

    <div class="form-group form-md-line-input">
        {!! Form::label( 'expire_date', trans( 'shop.fields.expire_date' ), ['class' => 'col-md-2 control-label'] ) !!}
        <div class="col-md-9">
            {!! Form::input( 'number', 'expire_date', NULL, ['class' => 'form-control'] ) !!}
            <div class="form-control-focus"> </div>
        </div>
    </div>

    <div class="form-group form-md-line-input">
        {!! Form::label( 'discount', trans( 'shop.fields.discount' ), ['class' => 'col-md-2 control-label'] ) !!}
        <div class="col-md-9">
            {!! Form::input( 'number', 'discount', NULL, ['class' => 'form-control'] ) !!}
            <div class="form-control-focus"> </div>
        </div>
    </div>
    <div class="form-group form-md-radios">
        <label class="col-md-2 control-label">{{ trans( 'shop.fields.shareable.title' ) }}</label>
        <div class="md-radio-inline">
            <div class="md-radio">
                {!! Form::radio( 'shareable', 1, NULL, ['id' => 'yes', 'class' => 'md-radiobtn'] ) !!}
                <label for="yes">
                    <span class="inc"></span>
                    <span class="check"></span>
                    <span class="box"></span> {{ trans( 'shop.fields.shareable.yes' ) }} </label>
            </div>
            <div class="md-radio">
                {!! Form::radio( 'shareable', 0, NULL, ['id' => 'no', 'class' => 'md-radiobtn'] ) !!}
                <label for="no">
                    <span class="inc"></span>
                    <span class="check"></span>
                    <span class="box"></span> {{ trans( 'shop.fields.shareable.no' ) }} </label>
            </div>
        </div>
    </div>

    <div class="form-group form-md-line-input">
        {!! Form::label( 'description', trans( 'shop.fields.description' ), ['class' => 'col-md-2 control-label'] ) !!}
        <div class="col-md-9">
            {!! Form::textarea( 'description', NULL, ['id' => 'summernote', 'class' => 'form-control'] ) !!}
            <div class="form-control-focus"> </div>
        </div>
    </div>

</div>
<div class="form-actions">
    <div class="row">
        <div class="col-md-offset-2 col-md-9">
            {!! Form::submit( $submitButtonText, ['id' => 'form_submit', 'class' => 'btn green'] ) !!}
        </div>
    </div>
</div>

@section( 'footer' )
    @parent
    <script>
        $('#summernote').summernote({height: 300});

        $('#form_submit').click(function () {
            $('input[name="description"]').val( $(".summernote").code() );
        });
    </script>
@endsection

resources/views/admin/shop/settings.blade.php
@extends( 'admin.header' )

@section( 'content' )
    <div class="portlet light bordered">
        <div class="portlet-body form">
            <form action="{{ url( 'admin/shop/settings' ) }}" method="post" class="form-horizontal">
                {!! csrf_field() !!}
                <div class="form-body">
                    <div class="form-group form-md-line-input">
                        <label class="col-md-2 control-label" for="items_per_page">{{ trans( 'shop.items_per_page' ) }}</label>
                        <div class="col-md-9">
                            <input name="items_per_page" type="number" class="form-control" id="items_per_page" value="{{ settings( 'shop_items_per_page' ) }}">
                            <div class="form-control-focus"> </div>
                            <span class="help-block">{{ trans( 'shop.items_per_page_desc' ) }}</span>
                        </div>
                    </div>
                </div>
                <div class="form-actions">
                    <div class="row">
                        <div class="col-md-offset-2 col-md-9">
                            <button type="submit" class="btn green">{{ trans( 'main.save_settings' ) }}</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/shop/view.blade.php
@extends( 'admin.header' )

@section( 'content' )
    @if( $items->count() > 0 )
        @foreach( $items as $item )
            <div class="col-md-4">
                <div class="grid-item box bg-white">
                    <div class="grid_icon">
                        <img src="{{ asset( File::exists( base_path( 'public/img/icons/' . $item->item_id . '.gif' ) ) ? 'img/icons/' . $item->item_id . '.gif' : 'img/icons/0.gif' ) }}" alt="{{ $item->name }}">
                    </div>
                    <div class="grid-item-title">
                        <span class="font-dark" id="name">{{ $item->name }}</span>
                    </div>
                    <div class="grid-item-price font-blue">
                        @if ( $item->discount)
                            <s>{{ $item->price }}</s> <span class="font-red">{{ $item->price - ( ( $item->price / 100 ) * $item->discount ) }}</span> {{ settings( 'currency_name' ) }}
                        @else
                            {{ $item->price . ' ' . settings( 'currency_name' ) }}
                        @endif
                    </div>
                    <div class="caption mt-xs p-sm">
                        @if ( !File::exists( base_path( 'public/img/icons/' . $item->item_id . '.gif' ) ) )
                            <div class="note note-danger">
                                <h4 class="block">{{ trans( 'shop.missing.title' ) }}</h4>
                                <p> {!! trans( 'shop.missing.body', ['path' => base_path( 'public/img/icons/' ), 'id' => $item->item_id] ) !!} </p>
                            </div>
                        @endif
                        <div class="scroller" style="height:100px" data-always-visible="1" data-rail-visible="1" data-rail-color="#111" data-handle-color="#000">
                            {!! $item->description !!}
                        </div>
                        <div class="grid-item-buy text-center mt-md">
                            <div class="text-center fs20">
                                <a class="font-green tooltips mr-md" data-placement="top" data-original-title="{{ trans( 'main.edit' ) }}" href="{{ route( 'admin.shop.edit', $item->id ) }}"><i class="icon-pencil"></i></a>
                                <a class="font-red tooltips delete" data-placement="top" data-original-title="{{ trans( 'main.remove' ) }}" href="{{ route( 'admin.shop.destroy', $item->id ) }}"><i class="icon-trash"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        @endforeach
    @else
        <div class="text-center">
            <h4> {{ trans( 'main.no_results') }} </h4>
        </div>
    @endif

    <div class="text-center">
        {!! $items->render() !!}
    </div>
@endsection

@section( 'footer' )
    @parent
    <script>
        $('.delete').click(function (e) {
            e.preventDefault();
            e.stopPropagation();

            var item_name = $(this).closest('div.col-md-4').find('#name').html();

            $.ajax({
                method: 'DELETE',
                url: $(this).attr('href'),
                data: {
                    '_token' : "{{ csrf_token() }}"
                },
                success: function (response) {
                    $('div.col-md-4').filter(function() {
                        return $(this).find('#name').text() === item_name
                    }).remove();
                },
                error: function (response) {
                    // handle error
                }
            });
        });
    </script>
@endsection